/**
 * Agent context generator - creates the agent-context-claude.md file
 * based on the project analysis results.
 */

import path from 'path';
import type { ProjectProfile } from '../types.js';
import { writeText, exists } from '../utils/file-ops.js';

/**
 * Generates an agent-context-claude.md file for the target project.
 */
export async function generateAgentContext(
  profile: ProjectProfile,
  targetPath: string,
  dryRun: boolean = false
): Promise<{ created: boolean; warnings: string[] }> {
  const contextPath = path.join(targetPath, '.specify', 'memory', 'agent-context-claude.md');

  if (await exists(contextPath)) {
    return {
      created: false,
      warnings: ['agent-context-claude.md already exists - not overwriting'],
    };
  }

  if (dryRun) {
    return { created: true, warnings: [] };
  }

  const content = generateContextContent(profile);
  await writeText(contextPath, content);

  return { created: true, warnings: [] };
}

function generateContextContent(profile: ProjectProfile): string {
  const sections: string[] = [];

  sections.push(`# Agent Context - ${profile.projectName}`);
  sections.push(`\nGenerated by SpecKit Deployer on ${new Date().toISOString()}\n`);

  // Tech Stack
  sections.push('## Tech Stack\n');
  if (profile.language) {
    sections.push(`- **Language**: ${profile.language}`);
  }
  if (profile.framework) {
    sections.push(`- **Framework**: ${profile.framework}`);
  }
  if (profile.database) {
    sections.push(`- **Database ORM**: ${profile.database}`);
  }
  if (profile.testFramework) {
    sections.push(`- **Testing**: ${profile.testFramework}`);
  }
  if (profile.cicd) {
    sections.push(`- **CI/CD**: ${profile.cicd}`);
  }

  // Project Status
  sections.push('\n## Project Status\n');
  sections.push(`- **Git**: ${profile.hasGit ? 'Initialized' : 'Not initialized'}`);
  sections.push(`- **SpecKit**: ${profile.hasSpecKit ? 'Previously installed' : 'Freshly deployed'}`);
  sections.push(`- **Beads**: ${profile.hasBeads ? 'Previously installed' : 'Freshly deployed'}`);
  sections.push(`- **Constitution Profile**: ${profile.suggestedProfile}`);

  // Existing Configuration
  if (profile.existingSpecialties.length > 0) {
    sections.push('\n## Existing Specialties\n');
    for (const specialty of profile.existingSpecialties) {
      sections.push(`- ${specialty}`);
    }
  }

  if (profile.existingMcpServers.length > 0) {
    sections.push('\n## Existing MCP Servers\n');
    for (const server of profile.existingMcpServers) {
      sections.push(`- ${server}`);
    }
  }

  // Working Patterns
  sections.push('\n## Working Patterns\n');
  sections.push('### Feature Development Workflow');
  sections.push('1. Create feature spec: `.specify/scripts/bash/create-new-feature.sh`');
  sections.push('2. Fill in spec.md using `.specify/templates/spec-template.md`');
  sections.push('3. Create plan: `.specify/scripts/bash/setup-plan.sh`');
  sections.push('4. Fill in plan.md with Constitution Check gate table');
  sections.push('5. Break down tasks in tasks.md');
  sections.push('6. Sync tasks to Beads: `.specify/scripts/bash/sync-beads.sh`');
  sections.push('7. Implement in phases');
  sections.push('8. Verify against acceptance criteria\n');

  sections.push('### Key Directories');
  sections.push('- `specs/` - Feature specifications');
  sections.push('- `.specify/` - SpecKit configuration and templates');
  sections.push('- `.specify/memory/constitution.md` - Project governance');
  sections.push('- `.beads/` - Task tracking');
  sections.push('- `.claude/skills/` - Available agent specialties');

  return sections.join('\n');
}
