/**
 * Constitution generator - adapts the base constitution template
 * for a target project based on its profile.
 */

import path from 'path';
import type { ProjectProfile, ConstitutionProfile, PrincipleStatus } from '../types.js';
import { readText, writeText, exists, getLibraryRoot } from '../utils/file-ops.js';

/**
 * Generates an adapted constitution for the target project.
 * NEVER overwrites an existing constitution.
 */
export async function generateConstitution(
  profile: ProjectProfile,
  targetPath: string,
  dryRun: boolean = false
): Promise<{ created: boolean; path: string; warnings: string[] }> {
  const constitutionPath = path.join(targetPath, '.specify', 'memory', 'constitution.md');
  const warnings: string[] = [];

  // Never overwrite existing constitution
  if (await exists(constitutionPath)) {
    return {
      created: false,
      path: constitutionPath,
      warnings: ['Constitution already exists - not overwriting. Edit manually if needed.'],
    };
  }

  if (dryRun) {
    return { created: true, path: constitutionPath, warnings: [] };
  }

  // Try to load base constitution from library
  const libraryRoot = getLibraryRoot();
  const basePath = path.join(libraryRoot, 'speckit', 'memory', 'constitution-base.md');
  let baseConstitution = await readText(basePath);

  if (!baseConstitution) {
    // Generate a default constitution if the library base doesn't exist yet
    baseConstitution = generateDefaultConstitution(profile);
    warnings.push('Base constitution not found in library - generated default');
  }

  // Append the constitution check gate table
  const gateTable = generateGateTable(profile.principleAdaptations);
  const fullConstitution = baseConstitution + '\n\n' + gateTable;

  await writeText(constitutionPath, fullConstitution);

  return { created: true, path: constitutionPath, warnings };
}

/**
 * Generates the Constitution Check gate table for plan.md files.
 */
function generateGateTable(adaptations: Record<string, PrincipleStatus>): string {
  const principleNames: Record<string, string> = {
    'I-crm-first': 'I. CRM-First Architecture',
    'II-plugin-ecosystem': 'II. Plugin Ecosystem',
    'III-api-first': 'III. API-First Development',
    'IV-client-isolation': 'IV. Client Isolation',
    'V-soc2-audit': 'V. SOC 2 / Audit Logging',
    'VI-cost-tracking': 'VI. Cost Tracking',
    'VII-deviation-prevention': 'VII. Deviation Prevention',
    'VIII-token-conservation': 'VIII. Token Conservation',
    'IX-structured-tools': 'IX. Structured Tools',
    'X-code-quality': 'X. Code Quality',
    'XI-context-first': 'XI. Context-First Decision Making',
    'XII-confirmation-points': 'XII. Confirmation Points',
    'XIII-bounded-loops': 'XIII. Bounded Loops',
    'XIV-ui-ux-first': 'XIV. UI/UX First Design',
    'XV-aws-only': 'XV. AWS-Only Infrastructure',
    'XVI-mcp-first': 'XVI. MCP-First Research',
    'XVII-research-phase': 'XVII. Research Phase',
    'XVIII-validation-phase': 'XVIII. Validation Phase',
    'XIX-implementation-phase': 'XIX. Implementation Phase',
    'XX-automation-patterns': 'XX. Automation Patterns',
  };

  let table = `## Constitution Check - Gate Table

This table MUST be included in every plan.md. All applicable principles must PASS before implementation begins.

| Principle | Status | Notes |
|-----------|--------|-------|
`;

  for (const [id, status] of Object.entries(adaptations)) {
    const name = principleNames[id] || id;
    const notes = status === 'N/A' ? 'Not applicable to this project type' :
                  status === 'DEVIATION' ? 'Documented deviation - see Complexity Tracking' :
                  status === 'PASS' ? 'Enforced' : '';
    table += `| ${name} | ${status} | ${notes} |\n`;
  }

  return table;
}

/**
 * Generates a default constitution when the library base isn't available.
 */
function generateDefaultConstitution(profile: ProjectProfile): string {
  return `# Project Constitution
## Version: 1.0.0
## Profile: ${profile.suggestedProfile}
## Project: ${profile.projectName}

---

## Overview

This constitution defines the governance principles for this project.
It was generated by the SpecKit Deployer and should be customized for your project's needs.

---

## Core Principles

### I. CRM-First Architecture
All customer data flows through a central CRM. Every interaction is logged and traceable.

### II. Plugin Ecosystem
The system is designed as a platform with pluggable modules, not a monolith.

### III. API-First Development
Every feature exposes a REST/GraphQL API before building UI. Contracts are defined before implementation.

### IV. Client Isolation
All data and operations are scoped by client/tenant ID. No data leaks between tenants.

### V. SOC 2 / Audit Logging
All mutations are logged via \`logAudit()\`. Every state change has a traceable audit trail.

### VI. Cost Tracking
External API calls, AI token usage, and resource consumption are tracked per operation.

### VII. Deviation Prevention
Any deviation from these principles must be documented with justification in the plan's Complexity Tracking section.

### VIII. Token Conservation
AI interactions follow token conservation rules. Complete one step at a time. Wait for confirmation before proceeding.

### IX. Structured Tools
Use specialized tools (Read, Edit, Write, Glob, Grep) instead of raw shell commands.

### X. Code Quality
Enforce type annotations, clear docstrings, and unit tests. Respect architectural patterns.

### XI. Context-First Decision Making
Research before implementation. Understand the existing codebase before proposing changes.

### XII. Confirmation Points
Ask for confirmation before creating files, making architectural changes, or running destructive commands.

### XIII. Bounded Loops
All iterative processes have max iterations, token budgets, and escalation rules. No unbounded loops.

### XIV. UI/UX First Design
Design the user interface before writing backend code. Use consistent design systems.

### XV. AWS-Only Infrastructure
All infrastructure runs on AWS. No local development servers in production workflows.

### XVI. MCP-First Research
Use MCP tools (ref.tools, exa) for documentation lookup before implementing features.

### XVII. Research Phase
Before implementing any feature, research official API docs, best practices, and known issues.

### XVIII. Validation Phase
Confirm the approach aligns with researched best practices before writing code.

### XIX. Implementation Phase
Apply patterns found during research. Reference documentation for correct API usage.

### XX. Automation Patterns
Use canonical patterns: Trigger-Route, Filter-Fan, Collector, Loop, Transformer, Watcher.

---

## Enforcement

Every plan.md must include a Constitution Check gate table.
Every deviation must be documented in the plan's Complexity Tracking section.
`;
}
